eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-log/**
      serviceId: chat-log-service
    api-b:
      path: /api-user/**
      serviceId: chat-user-service # service-feign