eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8769
spring:
  application:
    name: service-zuul
    #配置redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password: password
    pool:
      #最大连接数
      max-active: 8
      #阻塞时间
      max-wait: -1
      #最大空闲
      max-idle: 8
      #最小空闲
      min-idle: 0
#配置具体的路由映射
zuul:
  routes:
    api-a:
      path: /api-log/**
      serviceId: chat-log-service
    api-b:
      path: /api-user/**
      serviceId: chat-user-service # service-feign