eureka:
  client:
    serviceUrl:
     defaultZone: http://192.168.31.71:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8769
spring:
  application:
    name: service-zuul
#配置具体的路由映射
zuul:
  routes:
    api-a:
      path: /api-log/**
      serviceId: chat-log-service
    api-b:
      path: /api-user/**
      serviceId: chat-user-service # service-feign